[package]
name = "cardparty-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
jsonwebtoken = "9.3.0"
serde = {version = "1.0.203", features = ["serde_derive"]}
serde_json = "1.0.117"
